import { TGameState } from '../types'

export const TEST_GAME_STATE: TGameState = {
    round_number: 0,
    deck: [
        { suit: 'clubs', rank: '2' },
        { suit: 'clubs', rank: '7' },
        { suit: 'diamonds', rank: 'Q' },
        { suit: 'hearts', rank: '2' },
        { suit: 'clubs', rank: '4' },
        { suit: 'diamonds', rank: 'A' },
        { suit: 'hearts', rank: 'T' },
        { suit: 'diamonds', rank: '8' },
        { suit: 'spades', rank: '8' },
        { suit: 'hearts', rank: '5' },
        { suit: 'diamonds', rank: '6' },
        { suit: 'hearts', rank: 'K' },
        { suit: 'clubs', rank: '3' },
        { suit: 'diamonds', rank: 'K' },
        { suit: 'hearts', rank: 'Q' },
        { suit: 'clubs', rank: '9' },
        { suit: 'spades', rank: '3' },
        { suit: 'clubs', rank: 'T' },
        { suit: 'hearts', rank: '9' },
        { suit: 'diamonds', rank: '5' },
        { suit: 'clubs', rank: 'A' },
        { suit: 'spades', rank: '5' },
        { suit: 'spades', rank: '6' },
        { suit: 'diamonds', rank: 'T' },
    ],
    big_blind: 100,
    action_on: 0,
    dealer_position: 8,
    small_blind_position: 9,
    big_blind_position: 0,
    players: [
        {
            name: 'ME',
            description: 'The current human player',
            avatar: 'https://i.pravatar.cc/300',
            state: 'active',
            cards: [
                { suit: 'diamonds', rank: 'A' },
                { suit: 'diamonds', rank: '8' },
            ],
            showCards: true,
            stackSize: 9800,
            committedBet: 200,
            currentBet: 0,
        },
        {
            name: 'Jack',
            description:
                "Jack is a master of the mental game, using his calm demeanor to unsettle his opponents. He plays a balanced style, switching between passive and aggressive plays based on the table dynamics. Jack's ability to remain unfazed in high-pressure situations makes him a tough opponent, especially in high-stakes games where his calm approach can lead to significant payoffs.",
            avatar: 'https://i.pravatar.cc/300',
            state: 'all-in',
            cards: [
                { suit: 'clubs', rank: 'Q' },
                { suit: 'spades', rank: '2' },
            ],
            showCards: false,
            stackSize: 0,
            committedBet: 0,
            currentBet: 1000,
            action: {
                type: 'all_in',
                amount: 1000,
            },
        },
        {
            name: 'Isabella',
            description:
                "Isabella is known for her aggressive yet calculated playstyle. She's a risk-taker, often seen making big bluffs and large bets to put pressure on her opponents. However, her play is backed by a strong understanding of statistics and probability. Isabella's aggressive tactics are balanced with a keen sense of timing, knowing exactly when to fold or push her chips to the middle.",
            avatar: 'https://i.pravatar.cc/300',
            state: 'folded',
            cards: [
                { suit: 'spades', rank: 'K' },
                { suit: 'spades', rank: 'T' },
            ],
            showCards: false,
            stackSize: 10000,
            committedBet: 0,
        },
        {
            name: 'Sophia',
            description:
                "Sophia plays a tight and disciplined game, choosing her moments to strike with precision. Her playstyle is cautious yet opportunistic, making her a formidable opponent in the late stages of tournaments. Sophia's ability to remain patient and wait for high-value hands allows her to maintain her chip stack and apply pressure when it counts the most.",
            avatar: 'https://i.pravatar.cc/300',
            state: 'folded',
            cards: [
                { suit: 'diamonds', rank: 'J' },
                { suit: 'hearts', rank: '3' },
            ],
            showCards: false,
            stackSize: 10000,
            committedBet: 0,
        },
        {
            name: 'Emily',
            description:
                "Emily's playstyle is analytical and detail-oriented. She excels in games that require deep strategic thinking and has a knack for uncovering her opponents' strategies. Emily's approach to poker is methodical, with each move carefully calculated to maximize her chances of winning. Her disciplined play makes her a consistent performer in tournaments.",
            avatar: 'https://i.pravatar.cc/300',
            state: 'folded',
            cards: [
                { suit: 'spades', rank: '9' },
                { suit: 'hearts', rank: '8' },
            ],
            showCards: false,
            stackSize: 10000,
            committedBet: 0,
        },
        {
            name: 'Jerry',
            description:
                'Jerry is the epitome of professionalism at the poker table. He has a keen understanding of positional play and often uses his seat to leverage bets, regardless of his hand. Preferring strategic aggression, Jerry is known to raise the stakes when in the dealer position, even with low hands. His favorite hand, 4 6, is famously played with a surprising success rate, showcasing his ability to turn the tides in his favor. His poker face is unreadable, making it hard for opponents to gauge his strategy.',
            avatar: 'https://i.pravatar.cc/300',
            state: 'folded',
            cards: [
                { suit: 'spades', rank: 'Q' },
                { suit: 'spades', rank: '7' },
            ],
            showCards: false,
            stackSize: 9900,
            committedBet: 0,
            currentBet: 100,
        },
        {
            name: 'Noah',
            description:
                "Noah's poker style is aggressive and intimidating. He's known for his large bets and willingness to challenge his opponents head-on. Noah's ability to maintain a strong table presence allows him to control the game's pace, often leading his opponents to make mistakes under pressure. His bold playstyle makes him a dominant force in no-limit games.",
            avatar: 'https://i.pravatar.cc/300',
            state: 'folded',
            cards: [
                { suit: 'clubs', rank: 'Q' },
                { suit: 'spades', rank: '2' },
            ],
            showCards: false,
            stackSize: 10000,
            committedBet: 0,
        },
        {
            name: 'Chris',
            description:
                'Chris is an aggressive player who believes in applying constant pressure on his opponents. Known for his bold bluffs and unexpected raises, he keeps the table on edge. Chris excels in short-handed play, where his aggressive tactics often lead to quick chip accumulation. However, his play is not reckless; he has a deep understanding of odds and pot equity, making his aggressive moves calculated risks rather than wild gambles.',
            avatar: 'https://i.pravatar.cc/300',
            state: 'folded',
            cards: [
                { suit: 'hearts', rank: '6' },
                { suit: 'diamonds', rank: '7' },
            ],
            showCards: false,
            stackSize: 10000,
            committedBet: 0,
        },
        {
            name: 'Zoey',
            description:
                "Zoey's playstyle is dynamic and adaptable. She excels in reading the table and adjusting her strategy accordingly. Known for her mixed play, she balances between aggressive bets and cautious folds, making her a complex opponent to read. Zoey's strength lies in her psychological gameplay, where she excels in picking up on tells and exploiting her opponents' weaknesses, often leading them to make costly mistakes.",
            avatar: 'https://i.pravatar.cc/300',
            state: 'folded',
            cards: [
                { suit: 'spades', rank: 'A' },
                { suit: 'diamonds', rank: '2' },
            ],
            showCards: false,
            stackSize: 9950,
            committedBet: 0,
            currentBet: 50,
        },
        {
            name: 'Charlotte',
            description:
                "Charlotte's playstyle is characterized by her aggressive betting and strong table presence. She's a fearless player, often taking control of the game with her assertive plays. Charlotte's ability to read her opponents and anticipate their moves makes her a formidable competitor, capable of turning any game in her favor.",
            avatar: 'https://i.pravatar.cc/300',
            state: 'all-in',
            cards: [
                { suit: 'diamonds', rank: '7' },
                { suit: 'diamonds', rank: 'J' },
            ],
            showCards: false,
            stackSize: 0,
            committedBet: 200,
            currentBet: 9800,
            action: {
                type: 'all_in',
                amount: 9800,
            },
        },
    ],
    communityCards: [
        { suit: 'diamonds', rank: '6' },
        { suit: 'diamonds', rank: 'Q' },
        { suit: 'spades', rank: '7' },
    ],
    round_history: [
        { type: 'call', amount: 100, playerIndex: 0 },
        { type: 'call', amount: 100, playerIndex: 0 },
        { type: 'fold', playerIndex: 0 },
        { type: 'fold', playerIndex: 0 },
        { type: 'fold', playerIndex: 0 },
        { type: 'call', amount: 100, playerIndex: 0 },
        { type: 'fold', playerIndex: 0 },
        { type: 'fold', playerIndex: 0 },
        { type: 'fold', playerIndex: 0 },
        { type: 'raise', amount: 200, playerIndex: 0 },
        { type: 'call', amount: 200, playerIndex: 0 },
        { type: 'fold', playerIndex: 0 },
        { type: 'fold', playerIndex: 0 },
        {
            type: 'table_event',
            playerIndex: 0,
            cards_dealt: [
                { suit: 'clubs', rank: 'K' },
                { suit: 'hearts', rank: 'A' },
                { suit: 'diamonds', rank: '9' },
            ],
        },
        { type: 'check', playerIndex: 0 },
        { type: 'check', playerIndex: 0 },
        {
            type: 'table_event',
            cards_dealt: [{ suit: 'spades', rank: '4' }],
            playerIndex: 0,
        },
        { type: 'check', playerIndex: 0 },
        { type: 'check', playerIndex: 0 },
        {
            type: 'table_event',
            cards_dealt: [{ suit: 'diamonds', rank: '4' }],
            playerIndex: 0,
        },
        { type: 'check', playerIndex: 0 },
        { type: 'check', playerIndex: 0 },
    ],
    winners: {},
}
